atsService:
  api:
    url: https://adminapi.curately.ai/ats-service-prod

spring:
  application:
    name: ats-scheduler-prod
  datasource:
    username: accuickuser
    url: jdbc:sqlserver://52.32.184.206:51980;DatabaseName=Curately;encrypt=false;trustServerCertificate=true;
    password: ${PROD_DB_PASSWORD}

aws:
  s3:
    bucketName: ovastorage
    resumeLocation: curately/Sevron/
  sns:
    bullhornTopicArn: arn:aws:sns:us-west-2:068652499116:bullhorn-events-prod
    jobDivaTopicArn: arn:aws:sns:us-west-2:068652499116:jobdiva-events-prod
    agileOneTopicArn: arn:aws:sns:us-west-2:068652499116:agileone-events-prod
    emailOneTopicArn: arn:aws:sns:us-west-2:068652499116:ats-email-topic-prod


scheduled:
  bullhorn:
    enabled: true
    cronExpression: 0 0/5 * * * ?
  jobDiva:
    client: 54
    recruiter: 2
    jobAgentSearch:
      cronExpression: "0 0/5 * * * ?"
      enabled: true
    applicants:
      enabled: true
      cronExpression: "0 */15 * * * ?"
    candidateNotes:
      enabled: true
      cronExpression: "0 0/15 * * * ?"
  agileOne:
    recruiter: 3761
    job:
      enabled: true
      cronExpression: "0 */30 * * * ?"
    assignment:
      enabled: true
      cronExpression: "0 */25 * * * ?"

jobDiva:
  resumeCount: 300